### ISSUE TITLE
cleanup the project

### ISSUE THREAD

**Issue by Java8Test** [evgenybritan/parser#22]
Let's make readable structure of project:
My understanding that we should have the following parts:
- sdp library
- gui 
- test
- utils
sdp library. It is core of this project, which do packet parsing, and can generate packets.
- parser. Do parse, validate data, provide packet info
- generator. Do packet generation.

gui. it is some util to show usage of sdp library

test. consists of test data e.g. valid/invalid packets etc, and list of tests, so we can check sdp library.

I suggest each part should be placed in separate folder.

utils
All other temp data should be removed, or placed in utils if it is reasonable.

**Comment by evgenybritan** [comment]
https://github.com/evgenybritan/parser/commit/34199afbd90a2cdde3efb93066ae5fc4d4ea5974
